# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tvm < Formula
  desc "tvm - Terraform Version Manager"
  homepage "https://www.thorsten-hans.com"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ThorstenHans/tvm/releases/download/v0.0.3/tvm_darwin_arm64_0.0.3.tar.gz"
      sha256 "f2351ea734fbd607f45fd11f18f39060af1af38cdbb8c41bdaf40357f01aff2c"

      def install
        bin.install "tvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ThorstenHans/tvm/releases/download/v0.0.3/tvm_darwin_amd64_0.0.3.tar.gz"
      sha256 "647e2b9dece631bd82c93a2660739fcb2bce54709e4148358df00883e7c81c4b"

      def install
        bin.install "tvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThorstenHans/tvm/releases/download/v0.0.3/tvm_linux_arm64_0.0.3.tar.gz"
      sha256 "ec37c1e8d9376afc87d03472f0c088d98840e5975ed611e6e2606a428e453738"

      def install
        bin.install "tvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ThorstenHans/tvm/releases/download/v0.0.3/tvm_linux_amd64_0.0.3.tar.gz"
      sha256 "94d715278d704fca60e990f084bfa512dc0dce66b7adcb9ca8d54e4c87bccefe"

      def install
        bin.install "tvm"
      end
    end
  end

  conflicts_with "terraform"
end
